name: 'Install'
description: 'Install'

inputs:
    node_version:
        description: 'node_version'
        required: false
        default: 16.15.1

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node_version }}
        - uses: actions/cache@v3
          id: yarn-cache
          with:
              path: |
                  **/node_modules
                  ${{ github.workspace }}/node_modules
              key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}
        - name: Install
          shell: bash
          run: yarn --frozen-lockfile
