name: Bot message

on:
  issue_comment:
    types:
    - created

jobs:
  chromatic-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/bot'}}
    steps:   
    - name: Like comment
      uses: actions/github-script@v5
      with:
        script: |
          const {owner, repo} = context.issue
          github.rest.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "+1",
          });  
    - name: Get PR SHA
      id: sha
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head   
    - name: POST new status to the Github API (pending)
      run: echo ${{ steps.sha.outputs.result }}
