name: Chromatic message

on:
  issue_comment:
    types:
    - created

jobs:
  chromatic-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/chromatic'}}
    steps:
    - name: Get PR SHA
      id: sha
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head.sha   
    - name: POST new status to the Github API (pending)
      run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.sha.outputs.result }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "pending",
            "context": "Chromatic",
            "description": "Waiting Chromatic to run..."
            }'    
    - uses: actions/checkout@v2
      with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    
    - name: Chromatic
      id: chr
      run: | 
        BUILD_URL="https://bbb"
        STORYBOOK_URL="https://aaa" 
        echo "::set-output name=target_url::$STORYBOOK_URL"
    - name: POST new status to the Github API (success)
      run: |
          echo "${steps.chr.outputs.target_url}"
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.sha.outputs.result }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context": "Chromatic",
            "description": "Chromatic successfully completed ✅",
            "target_url":"${steps.chr.outputs.target_url}",
            "log_url":"${steps.chromatic.outputs.log_url}"
            }' 
    - name: POST new status to the Github API (failure)
      if: ${{ failure() }}
      run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.sha.outputs.result }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "failure",
            "context": "Chromatic",
            "description": "Chromatic failed",
            "target_url":"${steps.chromatic.outputs.target_url}",
            "log_url":"${steps.chromatic.outputs.log_url}"
            }' 

