name: Chromatic Comment
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
 
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
            trigger: '@chromatic'
        env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: | 
          yarn
          yarn chromatic
        if: steps.check.outputs.triggered == 'true'

