name: Chromatic
on:
  workflow_dispatch
 
jobs:
  install:
      uses: correttojs/flamingo/.github/workflows/install.yml@main
      
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn chromatic
