name: Chromatic
on:
  workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn install --prefer-offline --frozen-lockfile
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --prefer-offline --frozen-lockfile
      - run: npm run chromatic
