name: CI
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn
    
  codegen:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn codegen  
      
  typescript:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn tsc 
     
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:    
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn lint
    
  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - run: yarn test
