name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
      uses: correttojs/flamingo/.github/workflows/install.yml@main
     
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:    
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn lint
    - run: yarn stylelint "**/*.scss"
    
  codegen:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn codegen-tsc  
       
  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn test  
  
  build-storybook:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn build-storybook
