name: Lighthouse CI

on: [deployment_status]

jobs:
  lighthouse: 
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "sha ${{github.sha}}"
      - run: echo "sha ${GITHUB_SHA}"
      - run: echo "sha $(git rev-parse --short HEAD)"
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ github.event.deployment_status.target_url }}
          commentUrl: https://api.github.com/repos/${{github.repository}}/commits/${{github.sha}}/comments.
