name: PR Summary Check

on:
    pull_request:
        types:
            - edited
jobs:
    checkSummary:
        runs-on: ubuntu-latest
        outputs:
            checkbox: ${{ fromJSON(steps.checkbox.outputs.data).value }}
            waitForVercel: ${{ fromJSON(steps.checkbox.outputs.data).waitForVercel }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/typescript
              id: checkbox
              with:
                  filePath: './.github/build/pr_summary'
                  function: 'checkSummary'
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              env:
                  prEvent: ${{ toJson(github.event) }}
            - run: echo "${{ fromJSON(steps.checkbox.outputs.data).value }} - ${{ fromJSON(steps.checkbox.outputs.data).waitForVercel }}"

    Rebase:
        needs: checkSummary
        if: ${{ needs.checkSummary.outputs.checkbox == 'Rebase' }}
        uses: ./.github/workflows/pr_summary_rebase.yml
        with:
            prNumber: ${{  github.event.number }}
        secrets: inherit

    Vercel:
        needs: checkSummary
        if: ${{ contains( needs.checkSummary.outputs.checkbox, 'Vercel') }}
        uses: ./.github/workflows/pr_summary_vercel.yml
        with:
            prNumber: ${{  github.event.number }}
            branchName: ${{ github.event.pull_request.head.ref }} 
            check: ${{ needs.checkSummary.outputs.checkbox  }}
            sha: ${{ github.event.pull_request.head.sha  }}            
        secrets: inherit

    Chromatic-Check:
        needs: checkSummary
        if: ${{ contains(needs.checkSummary.outputs.checkbox, 'Chromatic') }}
        uses: ./.github/workflows/pr_summary_chromatic.yml
        with:
            prNumber: ${{  github.event.number }}
            branchName: ${{ github.event.pull_request.head.ref }}
            sha: ${{ github.event.pull_request.head.sha  }}
        secrets: inherit 
