name: PR Summary Sync

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    update-summary:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/typescript
              env:
                  BRANCH: ${{toJSON(github.event.pull_request.head.ref)}}
              with:
                  filePath: './.github/build/pr_summary'
                  function: 'init'
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      
     

