name: PR Summary Check

on:
    pull_request:
        types:  [opened, synchronize, edited] 
jobs:
    checkSummary:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/typescript
              with:
                  filePath: './.github/build/pr_summary'
                  function: 'checkSummary'
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              env:
                    prEvent: ${{ toJson(github.event) }}
                    PR_NUMBER: ${{  github.event.number }}
                    BRANCH_NAME: ${{ github.event.pull_request.head.ref }} 
                    CHECK: ${{ needs.checkSummary.outputs.checkbox  }}
                    SHA: ${{ github.event.pull_request.head.sha  }}  
                    CHROMATIC_PROJECT_TOKEN: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
                    repository: ${{ github.repository  }}
                    runId: ${{github.run_id}}
                    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
 
